name: helm-deploy

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
      helm-values-path:
        description: 'Path to the helm values file'
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        description: 'Name of the helm release'
        type: string
        default: 'todoapp'

jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up kind cluster
        uses: helm/kind-action@v1
        with:
          config: ./cluster.yml
          cluster_name: todoapp

      - name: Helm dry run
        run: |
          helm install todoapp ./todoapp-*.tgz \
            --dry-run --debug \
            -f ${{ inputs.helm-values-path }} \
            --set todoapp.image.version="${{ github.sha }}"

      - name: Deploy Helm to kind
        run: |
          helm upgrade --install todoapp ./todoapp-*.tgz \
            --atomic \
            --wait \
            --timeout 10m \
            --debug \
            -f ${{ inputs.helm-values-path }} \
            --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.password="${{ secrets.PASSWORD }}" \
            --set todoapp.secrets.login="${{ secrets.LOGIN }}" \
            --set todoapp.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            --set todoapp.image.version="${{ github.sha }}"